function Selection = importfilePW(filename, dataLines)
%IMPORTFILE Import data from a text file
%  BLINDCLIMBERS = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  BLINDCLIMBERS = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  BlindClimbers = importfile("G:\Il mio Drive\Computer\Documenti\University\PhD\Blind Climbers\experiments\NASA TLX\Blind-Climbers__Renato_001_PW_12-13-2022_14-41.csv", [9, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Dec-2022 20:17:40

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [9, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "BlindClimbers"];
opts.SelectedVariableNames = "BlindClimbers";
opts.VariableTypes = ["string", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "BlindClimbers"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
Selection = tbl.BlindClimbers;
end