function RatingScales = importfileRS(filename, dataLines)
%IMPORTFILE Import data from a text file
%  BLINDCLIMBERSADELE001RS121420220926 = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as a table.
%
%  BLINDCLIMBERSADELE001RS121420220926 = IMPORTFILE(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  BlindClimbersAdele001RS121420220926 = importfile("G:\Il mio Drive\Computer\Documenti\University\PhD\Blind Climbers\experiments\NASA TLX\Blind-Climbers__Adele_001_RS_12-14-2022_09-26.csv", [11, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Dec-2022 22:34:02

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [11, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Axes", "RatingScales"];
opts.VariableTypes = ["string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Axes", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Axes", "EmptyFieldRule", "auto");

% Import the data
RatingScales = readtable(filename, opts);
RatingScales = sortrows(RatingScales);
end